### ISSUE TITLE
Helm  descbinds breaks which key and prevents emacs from loading

### ISSUE THREAD

**Issue by EricaLinaG** [emacs-helm/helm-descbinds#33] opened 2024-03-31 16:39 UTC
## Expected behavior

I would expect that my configuration 
Continues to load as it always has. 
Not assert in helm code because I have turned which-key-mode on. 

## Actual behavior, from [`emacs-helm.sh`](https://github.com/emacs-helm/helm/wiki/Bugs#emacs-helmsh) if possible

Im sure this is a well known problem. 
And that it is not viewed that way here.
It would have been coded differently otherwise. 

On initialization. 
Signal - - Which key mode cannot be used with helm-descbinds.  Assert. 

## Steps to reproduce

Install fresh emacs, install and turn on which-key and helm-descbinds. 
Try to startup, assert instead.

Seems like this is all on purpose. It seems irresponsible to me.  Breaking the world instead of giving a reasonable warning and turning off helm's conflicting behavior is disrespectful.

## Backtraces (`M-x` [`toggle-debug-on-error`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Error-Debugging.html))

Asserts because which-key-mode is on. 
I'm sure you know where since it is on purpose, therefore blowing up on startup. 

## Describe versions of Helm, Emacs, operating system, etc.

Fresh system install. 
Current. Fresh install. 
Emacs 29.3
Current, fresh, arch Linux. 

- Helm:
- [Emacs](https://www.gnu.org/software/emacs/manual/html_node/elisp/Version-Info.html):
- OS:

**Comment by thierryvolpiatto** [comment] 2024-03-31 18:07
EricaLinaG ***@***.***> writes:

> Expected behavior
>
> I would expect that my configuration
> Continues to load as it always has.
> Not assert in helm code because I have turned which-key-mode on.

This is a duplicate of
https://github.com/emacs-helm/helm-descbinds/issues/32

> Actual behavior, from emacs-helm.sh if possible
>
> Im sure this is a well known problem.
> And that it is not viewed that way here.
> It would have been coded differently otherwise.
>
> On initialization.
> Signal - - Which key mode cannot be used with helm-descbinds. Assert.
>
> Steps to reproduce
>
> Install fresh emacs, install and turn on which-key and helm-descbinds.
> Try to startup, assert instead.
>
> Seems like this is all on purpose. It seems irresponsible to
> me. Breaking the world instead of giving a reasonable warning and
> turning off helm's conflicting behavior is disrespectful.

Please look at the previous issues and at the variables that are
provided to you before complaining.


Thanks.

> Backtraces (M-x toggle-debug-on-error)
>
> Asserts because which-key-mode is on.
> I'm sure you know where since it is on purpose, therefore blowing up on startup.
>
> Describe versions of Helm, Emacs, operating system, etc.
>
> Fresh system install.
> Current. Fresh install.
> Emacs 29.3
> Current, fresh, arch Linux.
>
>   • Helm:
>   • Emacs:
>   • OS:
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>

-- 
Thierry

**Closed** 2024-03-31 18:07 UTC
